### ISSUE TITLE
andrewberry/drupal_tests:0.3.3 not found

### ISSUE THREAD

**Issue by dakkusingh** [deviantintegral/drupal_tests#38]
```
Build-agent version 0.0.4761-f18e895 (2018-03-20T01:12:48+0000)
Starting container andrewberry/drupal_tests:0.3.3
  image cache not found on this host, downloading andrewberry/drupal_tests:0.3.3
Error response from daemon: manifest for andrewberry/drupal_tests:0.3.3 not found
```

I cannot see this 0.3.3 tag over at https://hub.docker.com/r/andrewberry/drupal_tests/tags/

**Comment by deviantintegral** [comment]
Oops. I forgot to manually add the new tag to docker hub (see https://github.com/deviantintegral/drupal_tests/issues/10 for the details as to why we can't use the default settings). It's building now, can you try again when it's done?

**Comment by dakkusingh** [comment]
@deviantintegral Thanks very much, reading through https://github.com/deviantintegral/drupal_tests/issues/10 also resolved a number of my own questions :D
