### ISSUE TITLE
Drupal 8.7.0 release.

### ISSUE THREAD

**Issue by Jaesin** [deviantintegral/drupal_tests#55]
Now that 8.7.0 has been released, we could make use of a 8.7.0 build.

**Comment by deviantintegral** [comment]
Totally agreed. Unfortunately, https://hub.docker.com/_/drupal _still_ doesn't have any 8.7.x releases up.

Their slowness in keeping their images updated (they are slow on security releases too), plus issues with autobuilds on Hub is leading me towards removing the dependency on that image and moving the next version to quay.io. My general plan is:

* Use the XML from updates.drupal.org to determine what the latest release is.
* Automatically download and validate it.
* Add a Circle CI job to run builds nightly to check for new releases, and automatically build / push them to quay.io.

**Comment by MegaChriz** [comment]
There seems to be a 8.7 build now: https://github.com/docker-library/drupal/blob/ed69be9cb28f4385255217ed98e04d2cb7dd014b/8.7/apache/Dockerfile

**Comment by deviantintegral** [comment]
I've been poking at this (work etc got busy over the last few months), and I've got a first stab at a command line tool to download core and validate it. It's certainly _more_ than what just this issue needs, but I had some other things I wanted to learn along the way too.

https://github.com/deviantintegral/drupal-update-client

Next step would be to use this to replace the existing download steps in the upstream dockerfile. One nice side effect is that we'll be able to test against multiple versions of core in the same base container (or at least a similar Dockerfile) now that there are multiple supported branches.

If anyone is truly blocked on testing (given that 8.6 is still supported), I'd be glad to merge the "straight forward" PRs that get us there.

**Comment by MegaChriz** [comment]
@deviantintegral I'm not blocked on this, I'm using a Docker container created by a co-worker now. I assume that container is based on this one, but since I don't know much about Docker, I'm not sure.

**Comment by deviantintegral** [comment]
FYI, working on 8.7 at https://github.com/deviantintegral/drupal_tests/pull/57 - Docker's upstream Drupal image switched PHP to 7.3 within the 8.6 branch, which broke rebuilds. I'll be looking to get that fixed soon so we can get an updated 8.6 image too.

**Comment by deviantintegral** [comment]
Actually, that was faster than I expected. I tagged `0.5.0-drupal87` (in prep for future releases that build multiple Drupal versions) this morning.
