### ISSUE TITLE
Fix new builds of the 8.6 branch

### ISSUE THREAD

**Issue by deviantintegral** [deviantintegral/drupal_tests#59]
Docker Hub changed upstream Drupal 8.6 to build against PHP 7.3. This breaks our build as we have some PHP 7.2 specific paths. Since upgrading PHP could be a major dxwtf, let's build against a specific PHP branch instead of using the Drupal image.

**Comment by m4olivei** [comment]
Looks like this was fixed in https://github.com/deviantintegral/drupal_tests/pull/57. Closing.
